languageCode = "en-us"
title = "Usable Software Ecosystem Research"
baseURL = "https://user-project.superbloom.design"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Researching how usability and design presents in scientific open source software, with the goal of investigating what are the conditions that enable scientific open source teams to prioritize and focus on usability successfully. This work is supported by the Sloan Foundation."
  codePenUser = "Heydon"