languageCode = "en-us"
title = "Usable Software Ecosystem Research"
baseURL = "https://user-project.superbloom.design"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Researching usability and design in scientific open source software, with support from the Alfred P. Sloan Foundation."
  codePenUser = "Heydon"
