languageCode = "en-us"
title = "Cupper"
baseURL = "https://subtle-medovik-58f1c6.netlify.app"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Cupper** documentation builder, built with **Cupper** itself."
  codePenUser = "Heydon"