backend:
  name: github
  repo: simplysecure/user_project_website
  branch: main
  site_domain: subtle-medovik-58f1c6.netlify.app

media_folder: 'static/images'
public_folder: '/images'

publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "about"
    label: "About USER"
    folder: "content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "findings"
    label: "Findings"
    folder: "content/findings"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "part-1-the-state-of-SROSS"
    label: "Part 1: The State of Science and Research Open Source Software (SROSS) Projects"
    folder: "content/part-1-the-state-of-SROSS"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "part-2-project-operations"
    label: "Part 2: Project Operations"
    folder: "content/part-2-project-operations"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "part-3-design"
    label: "Part 3: Design"
    folder: "content/part-3-design"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text", required: false }
      - { name: "tag", label: "Tag(s)", widget: "text", required: false  }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" } 