backend:
  name: github
  repo: simplysecure/user_project_website
  branch: main
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "URL Slug" }
      - { name: "author", label: "Author(s)", widget: "text" }
      - { name: "tag", label: "Tag(s)", widget: "text" }
      - { name: "featuredImage", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
